name: map_controller_plus
description: A map controller for Flutter map. Manage markers, lines and polygons.
homepage: https://github.com/TesteurManiak
repository: https://github.com/TesteurManiak/map_controller
version: 0.14.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ">=0.13.1 <0.15.0"
  geojson: ^1.0.0
  geopoint: ^1.0.0
  latlong2: ^0.8.1
  rxdart: ">=0.26.0 <0.28.0"

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  uses-material-design: true
