name: map_controller_plus
description: A map controller for Flutter map. Manage markers, lines and polygons.
homepage: https://github.com/TesteurManiak/map_controller_plus
repository: https://github.com/TesteurManiak/map_controller_plus
issue_tracker: https://github.com/TesteurManiak/map_controller_plus/issues
version: 2.0.0
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  geojson: ^1.0.0
  geopoint: ^1.0.0
  latlong2: ^0.8.1

dev_dependencies:
  fd_lints: ^1.0.2
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  mocktail: ^0.3.0
