name: map_controller
description: A map controller for Flutter map. Manage markers, lines and polygons.
homepage: https://github.com/TesteurManiak
repository: https://github.com/TesteurManiak/map_controller
version: 0.8.4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  extra_pedantic: ^1.1.1+3
  flutter_map: ^0.11.0
  geojson: ^0.9.1
  geopoint: ^0.7.1
  latlong: ^0.6.1
  meta: any
  pedantic: ^1.8.0
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
