name: Test workflow

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - name: Analyze project
        run: flutter analyze
        working-directory: ./lib
      - name: Run tests
        run: flutter test
